"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Copyright 2026 The Dapr Authors
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _InProcessWorkflow:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _InProcessWorkflowEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_InProcessWorkflow.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    IN_PROCESS_WORKFLOW_MCP: _InProcessWorkflow.ValueType  # 0
    """MCP: Model Context Protocol server orchestrations.
    Prefix: "dapr.internal.mcp."
    """

class InProcessWorkflow(_InProcessWorkflow, metaclass=_InProcessWorkflowEnumTypeWrapper):
    """InProcessWorkflow identifies a category of Dapr internal workflow.
    Workflow name format: dapr.internal.<workflow>.<resource>.<method>

    SDKs map enum values to string prefixes:
      IN_PROCESS_WORKFLOW_MCP → "dapr.internal.mcp."
    """

IN_PROCESS_WORKFLOW_MCP: InProcessWorkflow.ValueType  # 0
"""MCP: Model Context Protocol server orchestrations.
Prefix: "dapr.internal.mcp."
"""
Global___InProcessWorkflow: _TypeAlias = InProcessWorkflow  # noqa: Y015

class _MCPMethod:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _MCPMethodEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_MCPMethod.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    MCP_METHOD_LIST_TOOLS: _MCPMethod.ValueType  # 0
    """Discovers available tools on an MCPServer."""
    MCP_METHOD_CALL_TOOL: _MCPMethod.ValueType  # 1
    """Invokes a specific tool on an MCPServer."""

class MCPMethod(_MCPMethod, metaclass=_MCPMethodEnumTypeWrapper):
    """MCPMethod identifies an operation within the MCP internal workflow.
    SDKs map enum values to PascalCase method suffixes:
      MCP_METHOD_LIST_TOOLS → ".ListTools"
      MCP_METHOD_CALL_TOOL  → ".CallTool"
    """

MCP_METHOD_LIST_TOOLS: MCPMethod.ValueType  # 0
"""Discovers available tools on an MCPServer."""
MCP_METHOD_CALL_TOOL: MCPMethod.ValueType  # 1
"""Invokes a specific tool on an MCPServer."""
Global___MCPMethod: _TypeAlias = MCPMethod  # noqa: Y015
